<TABLE width="630" style="border-width: 1; border-style:solid; border-color: #06a5cd;">
	<TR>
		<TD width="130"> %%starttime%% - %%endtime%% </TD>
		<TD width="296"><b>%%name%%</b> </TD>
		<TD width="20" align="center"><img src="/images/prototype/listings/flag.gif"> </TD>
		<TD width="20" align="center"><img src="/images/prototype/listings/todo.gif"> </TD>
		<TD width="47" align="center"><img src="/images/prototype/listings/rsvp.gif"> </TD>
		<TD width="22" align="center"><img src="/images/prototype/listings/email.jpg" width="19" height="19"> </TD>
		<TD width="22" align="center"><a href="http://www.theyorker.co.uk/"> <img src="/images/prototype/listings/link.png" border="0"> </a></TD>
		<TD width="73" align="center"><img src="/images/prototype/listings/subscribe.jpg"></TD>
	</TR>
	<TR>
		<TD colspan="8">
			<TABLE border="0" width="100%">
				<TR>
					<TD valign="middle" width="50"><img src="/images/prototype/listings/map.jpg"> </TD>
					<TD> %%shortloc%% </TD>
					<TD> Organisation: <a href="">FragSoc</a> </TD>
					<TD> Section: <a href="">Speakers </a> </TD>
					<TD width="60" style="cursor:pointer; " onClick="showEventMore('event',%%arrid%%);"><img src="/images/prototype/listings/more.gif"></TD>
				</TR>
				<!--TR>
					<TD bgcolor="#FF6A00" valign="middle" width="50" align="center"  style="border-top-style: dotted; border-top-width: 1; border-top-color: #FF6A00;"><font color="white"><b>Yorker Preview</b></font></td>
					<TD valign="middle" colspan="4" height="50"  style="border-top-style: dotted; border-top-width: 1; border-bottom-style: dotted; border-bottom-width: 1; border-color: #FF6A00;"><P style="font-size: small;">There isn't some clear-cut formula for making a great game, but Epic hasn't ignored bullet-point features in expanding the Unreal Tournament series, which is now in its third installment. The multiplayer-focused first-person shooter series started off in 1999 with great graphics, crisp control, solid networking (which led to smooth online gameplay), and hectic action.</P></TD>
				</TR-->					
			</TABLE></TD>
	</TR>
</TABLE>
<DIV id="event%%arrid%%" style="display: none;">
	<TABLE width="630" height="100" style="border-width: 1; border-top-width: 0; border-style: dashed;  border-color: #06a5cd;">
		<TR>
			<TD valign="top">%%blurb%%</TD>
		</TR>
	</TABLE>
</DIV>
