
	calevents{%%day%%}{%%arrid%%} = new Object ();
	calevents{%%day%%}{%%arrid%%}{0:'%%refid%%'};
	calevents{%%day%%}{%%arrid%%}{ref_id:'%%refid%%'};
	calevents{%%day%%}{%%arrid%%}{name:'%%name%%'};
	calevents{%%day%%}{%%arrid%%}{date:'%%date%%'};
	calevents{%%day%%}{%%arrid%%}{day:'%%day%%'};
	calevents{%%day%%}{%%arrid%%}{starttime:'%%starttime%%'};
	calevents{%%day%%}{%%arrid%%}{endtime:'%%endtime%%'};
	calevents{%%day%%}{%%arrid%%}{blurb:'%%blurb%%'};
	calevents{%%day%%}{%%arrid%%}{shortloc:'%%shortloc%%'};
	calevents{%%day%%}{%%arrid%%}{type:'%%type%%'};

